// ============================================
// GLOSSARY (Dictionary of technical terms)
// ============================================
const GLOSSARY = {
  "environmental organizations": "Groups (governmental or non-governmental) whose main goal is to protect nature, ecosystems, and human health from environmental damage.",
  "energy production": "The process of generating electricity or usable energy from sources such as coal, gas, nuclear, wind, solar, or biomass.",
  "waste disposal": "The collection, treatment, recycling, or destruction of unwanted materials produced by households, industry, or agriculture.",
  "industrialized": "Describes a country with highly developed industry, manufacturing, and infrastructure — usually with high energy consumption.",
  "climate change": "Long-term changes in global temperatures and weather patterns, largely caused by human emissions of greenhouse gases like CO₂.",
  "EPA": "Environmental Protection Agency — the U.S. federal agency responsible for environmental laws, air/water standards, and pollution control.",
  "federal authority": "A government body that operates at the national level, with power over the entire country rather than just one state.",
  "regulations": "Official rules created by a government agency that industries and citizens must follow (e.g. emission limits).",
  "emissions": "Substances (especially gases like CO₂, NOx, methane) released into the atmosphere from vehicles, factories, or power plants.",
  "NGO": "Non-Governmental Organization — an independent group not run by any government, often working on environmental, social, or humanitarian issues.",
  "Sierra Club": "One of the largest and oldest environmental NGOs in the United States, campaigning for renewable energy and land conservation.",
  "renewable energy": "Energy from sources that naturally replenish, such as wind, solar, hydro, geothermal, and biomass.",
  "NRDC": "Natural Resources Defense Council — a U.S. environmental NGO that uses scientific research and lawsuits to influence policy.",
  "lobbying": "Trying to influence politicians and lawmakers to pass laws favorable to a certain cause or group.",
  "Umweltbundesamt": "The German Federal Environment Agency — the central scientific authority for environmental protection in Germany.",
  "BUND": "Bund für Umwelt und Naturschutz Deutschland — a major German environmental NGO focused on nature conservation and climate policy.",
  "NABU": "Naturschutzbund Deutschland — a German NGO focused on bird protection, biodiversity, and nature conservation.",
  "biodiversity": "The variety of plant and animal species in an ecosystem. High biodiversity means a healthier, more stable environment.",
  "climate protection": "Actions and policies aimed at reducing greenhouse gas emissions and limiting global warming.",
  "sustainable development": "Development that meets present needs without compromising the ability of future generations to meet theirs.",
  "state to state": "Meaning laws and standards can differ significantly between individual U.S. states rather than being uniform across the country.",
  "lawsuits": "Legal cases brought before a court — often used by U.S. environmental groups to force companies or governments to comply with laws.",
  "climate targets": "Officially set goals for reducing greenhouse gas emissions by a specific year (e.g. climate-neutral by 2045).",
  "incentives": "Financial rewards (subsidies, tax breaks, grants) offered to encourage certain behavior, such as installing solar panels.",
  "natural gas": "A fossil fuel (mostly methane) used for electricity generation and heating. Cleaner than coal but still emits CO₂.",
  "nuclear power": "Electricity generated by nuclear fission of uranium. Produces very little CO₂ but creates radioactive waste.",
  "Energiewende": "German term for the 'energy transition' — the national shift from fossil fuels and nuclear power toward renewable energy.",
  "biomass": "Organic material (wood, plants, agricultural waste) used as fuel to produce electricity or heat.",
  "phase out": "To gradually stop using something over a planned period of time — e.g. Germany's phase-out of nuclear power.",
  "fossil fuels": "Energy sources formed from ancient organic material: coal, oil, and natural gas. Burning them releases CO₂.",
  "grid infrastructure": "The system of power lines, transformers, and substations that transports electricity from producers to consumers.",
  "landfills": "Sites where solid waste is buried in the ground — the most common form of waste disposal in the USA.",
  "waste management": "The entire system of collecting, transporting, treating, recycling, and disposing of waste.",
  "waste separation": "Sorting household waste into different categories (paper, plastic, glass, organic, residual) to enable recycling.",
  "organic waste": "Biodegradable waste from food scraps, garden clippings, etc. Can be composted or turned into biogas.",
  "deposit system": "A refund system (called 'Pfand' in Germany) where consumers pay a small fee on bottles/cans and get it back when they return them.",
  "waste-to-energy": "Facilities that burn non-recyclable waste to generate electricity and heat, reducing landfill volume.",
  "recycling rate": "The percentage of a country's waste that is successfully recycled into new products instead of being landfilled or burned.",
  "standardized": "Uniform across a country — the same rules and categories apply everywhere, making the system easier to understand.",
  "infrastructure": "The basic physical systems and facilities (roads, power lines, recycling plants, etc.) needed for a society to function.",
  "market mechanisms": "Using economic forces (prices, competition, incentives) rather than strict regulation to achieve policy goals."
};

// ============================================
// SLIDE NAVIGATION
// ============================================
const slides = document.querySelectorAll('.slide');
const total = slides.length;
let current = 1;

const prevBtn = document.getElementById('prevBtn');
const nextBtn = document.getElementById('nextBtn');
const counter = document.getElementById('slideCounter');

function showSlide(n) {
  slides.forEach(s => s.classList.remove('active'));
  const target = document.querySelector(`.slide[data-slide="${n}"]`);
  if (target) target.classList.add('active');
  counter.textContent = `${n} / ${total}`;
  prevBtn.disabled = n === 1;
  nextBtn.disabled = n === total;
  window.scrollTo({ top: 0, behavior: 'smooth' });
}

prevBtn.addEventListener('click', () => { if (current > 1) { current--; showSlide(current); } });
nextBtn.addEventListener('click', () => { if (current < total) { current++; showSlide(current); } });

document.addEventListener('keydown', (e) => {
  if (e.key === 'ArrowRight' && current < total) { current++; showSlide(current); }
  if (e.key === 'ArrowLeft' && current > 1) { current--; showSlide(current); }
  if (e.key === 'Escape') closeGlossary();
});

showSlide(1);

// ============================================
// TERM POPUP (hover / click)
// ============================================
const termPopup = document.getElementById('termPopup');
const termTitle = termPopup.querySelector('.term-popup-title');
const termBody = termPopup.querySelector('.term-popup-body');

function showTermPopup(termEl) {
  const key = termEl.dataset.term.toLowerCase();
  const def = GLOSSARY[key] || GLOSSARY[termEl.dataset.term] || "No definition available. Try the full dictionary.";
  termTitle.textContent = termEl.dataset.term;
  termBody.textContent = def;
  const rect = termEl.getBoundingClientRect();
  termPopup.classList.remove('hidden');
  const popupRect = termPopup.getBoundingClientRect();
  let left = rect.left + window.scrollX;
  let top = rect.bottom + window.scrollY + 8;
  if (left + popupRect.width > window.innerWidth - 10) {
    left = window.innerWidth - popupRect.width - 10;
  }
  termPopup.style.left = left + 'px';
  termPopup.style.top = top + 'px';
}

function hideTermPopup() { termPopup.classList.add('hidden'); }

document.addEventListener('click', (e) => {
  if (e.target.classList.contains('term')) {
    e.stopPropagation();
    showTermPopup(e.target);
  } else if (!termPopup.contains(e.target)) {
    hideTermPopup();
  }
});

// ============================================
// GLOSSARY MODAL
// ============================================
const glossaryBtn = document.getElementById('glossaryBtn');
const glossaryModal = document.getElementById('glossaryModal');
const closeBtn = document.getElementById('closeGlossary');
const glossaryList = document.getElementById('glossaryList');
const glossarySearch = document.getElementById('glossarySearch');

function renderGlossary(filter = '') {
  const q = filter.toLowerCase().trim();
  const entries = Object.entries(GLOSSARY)
    .filter(([term, def]) => !q || term.toLowerCase().includes(q) || def.toLowerCase().includes(q))
    .sort((a, b) => a[0].localeCompare(b[0]));

  if (entries.length === 0) {
    glossaryList.innerHTML = '<p style="color:#FFD700;text-align:center;padding:20px;font-family:Georgia;">No matches found.</p>';
    return;
  }

  glossaryList.innerHTML = entries.map(([term, def]) => `
    <div class="glossary-entry">
      <div class="glossary-term">${term.toUpperCase()}</div>
      <div class="glossary-def">${def}</div>
    </div>
  `).join('');
}

function openGlossary() {
  glossaryModal.classList.remove('hidden');
  glossarySearch.value = '';
  renderGlossary();
  setTimeout(() => glossarySearch.focus(), 100);
}
function closeGlossary() { glossaryModal.classList.add('hidden'); }

glossaryBtn.addEventListener('click', openGlossary);
closeBtn.addEventListener('click', closeGlossary);
glossaryModal.addEventListener('click', (e) => {
  if (e.target === glossaryModal) closeGlossary();
});
glossarySearch.addEventListener('input', (e) => renderGlossary(e.target.value));
